import os
import numpy as np

# Define number of time steps
num_timesteps = 60

# Create the time steps automatically
timesteps = np.linspace(0, 1, num_timesteps)  # This will generate 60 evenly spaced time steps between 0 and 1

# Automatically get the folder of the current script
current_folder = os.path.dirname(os.path.realpath(__file__))

# VTK file names generated by the previous script
vtk_file_names = [f"Mungari_Sequence_with_NumericTime_{i}.vtu" for i in range(num_timesteps)]

# Create the PVD file
pvd_file_path = os.path.join(current_folder, 'Mungari_Sequence_with_NumericTime.pvd')

# Generate the PVD file content
with open(pvd_file_path, 'w') as f:
    f.write('<VTKFile type="Collection" version="0.1" byte_order="LittleEndian">\n')
    f.write('    <Collection>\n')
    for timestep, vtk_file in zip(timesteps, vtk_file_names):
        f.write(f'        <DataSet timestep="{timestep}" file="{vtk_file}"/>\n')
    f.write('    </Collection>\n')
    f.write('</VTKFile>')

print(f'PVD file saved as {pvd_file_path}')
